version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pmtool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pmtool
      SECRET_KEY: change-in-prod
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app

volumes:
  db_data:
